### ISSUE TITLE
Poetry run breaks typer

### ISSUE THREAD

**Issue by stratofax** [TrustTheVote-Project/BallotLab#15]
Using `poetry run ballotmaker` (or `poetry shell` and then `ballotmaker`) generates a Traceback message, which is not an error:

```
➤ poetry run ballotmaker
BallotMaker version: 0.1.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/neil/repos/ttv/BallotLab/src/electos/ballotmaker/cli.py", line 24, in main
    raise typer.Exit()
click.exceptions.Exit
```

Comment out `# raise typer.Exit()` on line 24 of `cli.py` to supress the Traceback output. However, the `--help` option doesn't work. 

Compare these two results, after `poetry shell` is invoked:

```➤ ballotmaker
BallotMaker version: 0.1.0
➤ ballotmaker --help
BallotMaker version: 0.1.0```
Versus:
```➤ python3 src/electos/ballotmaker/ --help
Usage: python -m  [OPTIONS]

  Create ballot PDFs from an Election Data File (EDF)

Options:
  --version                       Print the version number.
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.
➤ python3 src/electos/ballotmaker/ --version
BallotMaker version: 0.1.0```

Note that `python3 src/electos/ballotmaker/` produces *no* output in a `poetry shell`

**Comment by ion-oset** [comment]
The issue isn't Poetry specific. [Setuptools `console_scripts`](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation), [Poetry `scripts`](https://python-poetry.org/docs/pyproject/#scripts) and Python [packaging entry points](https://packaging.python.org/en/latest/specifications/entry-points/) all need a named function, and `"__main__"` isn't a  function, it's a special case module name. What makes it complicated is that the mechanism seems to need an actual _function_. The Typer decorated function isn't being recognized as such. So this doesn't work:

```
app = Typer(...)

@app.command
def main(...):
    ...

if __name__ == "__main__":
    app()
```

The solution is to give the CLI a guaranteed named function that's not a decorator, so one more level of indirection.


```
app = Typer(...)

@app.command
def cli(...):
    ...

def main():
    app()

if __name__ == "__main__":
    main()
```

**Comment by ion-oset** [comment]
The reason you are seeing a discrepancy in behavior between running `python src/electos/ballotmaker` with and without `poetry shell` has to do with the fact that `poetry shell` sets up the package for the entire project. Without it, there's no package and the script gets executed in the [top-level code environment](https://docs.python.org/3/library/__main__.html) aka the "__main__" pseudo-package. With it it gets executed in the package.

If you put a `print(f"__name__ == {__name__}")` at top-level scope in `cli.py` you'll see different results when you run`python src/electos/ballotmaker`:

- Outside of `poetry shell` you'll see: ```__name__ == __main__```. 
- Inside of `poetry shell` you'l see: ```electos.ballotmaker```

Since the if/main block inside poetry shell doesn't match `

**Comment by stratofax** [comment]
Do we need the console script at all? Not sure what it does for us, after checking the docs, at [The pyproject.toml file - scripts | Documentation | Poetry](https://python-poetry.org/docs/pyproject/#scripts)

In `pyproject.toml`, I’m going to comment out

```
[tool.poetry.scripts]
ballotmaker = 'electos.ballotmaker.cli:main'
```

to see what happens.

**Comment by ion-oset** [comment]
Yes. We absolutely need the console scripts. Console scripts allow scripts in package to remain portable across platforms, operating systems, and Python versions. They make `poetry run` work, and make it so you can ship a script `ballotmaker` and not need `python -m` or a source tree to make it run.

See:
- https://packaging.python.org/en/latest/specifications/entry-points/
- https://setuptools.pypa.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation

**Comment by stratofax** [comment]
OK, That makes sense. Can we change the scripts entry to:

```
ballotmaker = 'electos.ballotmaker.__main__
```

Since that's the expected entry point, and that will also execute app() in cli.py?

**Comment by stratofax** [comment]
Or can we use this line instead:

```
ballotmaker = 'electos.ballotmaker.cli:app'
```

Since app() is the function we want to call as the entry point, not main().

**Comment by stratofax** [comment]
OK, I see exactly why the Traceback was showing up, too. Good work on untangling this!

I think the solution is to revert `cli.py` and update `pyproject.toml` with the new entry point -- do you want to do that?

**Comment by ion-oset** [comment]
I didn't revert it, I just added a change to the PR on the `fix-entry-point` branch. Try it out.

**Comment by stratofax** [comment]
OK, `poetry run` works! Check it out when I **don't** use `poetry shell`:

```
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ poetry run ballotmaker --help
Usage: ballotmaker [OPTIONS]

  Create ballot PDFs from an Election Data File (EDF)

Options:
  --version                       Print the version number.
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ poetry run ballotmaker
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ poetry run ballotmaker --version
BallotMaker version: 0.1.0
```

**Comment by stratofax** [comment]
Sadly, `poetry shell` now throws an exception. This looks like I need to clear out the cache and regenerate the venv:

```
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ poetry shell
Spawning shell within /Users/neil/Library/Caches/pypoetry/virtualenvs/ballotlab-41lkk5zi-py3.9
Welcome to fish, the friendly interactive shell
[I] neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ source /Users/neil/Library/Caches/pypoetry/virtualenvs/ballotlab-41lkk5zi-py3.9/bin/activate.fish
[I] (ballotlab-41lkk5zi-py3.9) neil@Neils-Mac-mini:~/r/t/BallotLab|cli✓
➤ ballotmaker --help
Traceback (most recent call last):
  File "/Users/neil/Library/Caches/pypoetry/virtualenvs/ballotlab-41lkk5zi-py3.9/bin/ballotmaker", line 2, in <module>
    from electos.ballotmaker.cli import main
ImportError: cannot import name 'main' from 'electos.ballotmaker.cli' (/Users/neil/repos/ttv/BallotLab/src/electos/ballotmaker/cli.py)
```

**Comment by stratofax** [comment]
Fixed! Here's what I did:

**Comment by ion-oset** [comment]
Yeah that was my fault. My last change on PR #16 got rid of `main` - it was renamed to `cli` in [655a2ef4](https://github.com/TrustTheVote-Project/BallotLab/pull/16/commits/655a2ef4) and I forgot to change it back. Nothing to do with Poetry.
