### ISSUE TITLE
Too many __init__.py files?

### ISSUE THREAD

**Issue by stratofax** [TrustTheVote-Project/BallotLab#17]
Repo needs to be reviewed and cleaned up. How can we use the smallest number of __init__.py files?

**Comment by ion-oset** [comment]
Should be removed:

- `assets/schema/election`: Not only `__init__.py` but the entire directory can go away. It's replaced by [`electos.datamodels.nist.models.edf`](https://github.com/ion-oset/nist-data-models/tree/python/main/src/electos/datamodels/nist/models/edf)
- `src/__init__.py`: `src` is not a package. It should have any files.
- `src/electos/__init__.py`: `src/electos` is a namespace package. It cannot have files.
- `src/electos/versadm/...`: Unless I misunderstand, this whole folder should be under `electos/ballotmaker` or go away.

Should remain:

- `src/electos/ballotmaker/__init__.py`. There is code in `electos/ballotmaker` so it's not a namespace package and needs an `__init__.py` to import from.

**Comment by stratofax** [comment]
This is what I need to do, so I've assigned myself. Docs: [5. The import system: regular packages — Python 3.10.4 documentation](https://docs.python.org/3/reference/import.html#regular-packages)

**Comment by ion-oset** [comment]
That explanation of packages is a good thing to read. It will explain why one of those `__init__.py` files is currently an active problem: `src/electos/__init__.py` is making `electos` not be a namespace package. This breaks importing NISTlib from inside BallotLab.

Namespace packages are treated as if they were all the same directory when modules are imported. So even though `electos/ballotmaker` lives under src, and `electos/datamodels/nist` lives under `.venv/lib/python3.X/site-packages` you can still import from either of them.

If one of them is a regular package, it take precedence and blocks the other. Which means:

- Works: ```$ python -c 'import electos'```
- Works: ```$ python -c 'import electos.ballotmaker'```

- Fails (raises `ModuleNotFoundError`): ```$ python -c 'import electos.datamodels'```

So you have to do at least some of the cleanup before you can try out NISTlib models.

**Comment by stratofax** [comment]
Merged on main with automation
