### ISSUE TITLE
Import EDF using NISTLib

### ISSUE THREAD

**Issue by stratofax** [TrustTheVote-Project/BallotLab#21]
Any valid EDF will do at this point!

**Comment by stratofax** [comment]
Use the `validate` sub-command; see for details [BallotMaker CLI commands · Discussion #23 · TrustTheVote-Project/BallotLab](https://github.com/TrustTheVote-Project/BallotLab/discussions/23)

**Comment by stratofax** [comment]
Next: I create the `validate` branch on my fork and build this

**Comment by stratofax** [comment]
When my code is reviewed and approved, I'll merge it onto this new branch, [TrustTheVote-Project/BallotLab at validate](https://github.com/TrustTheVote-Project/BallotLab/tree/validate)

**Comment by ion-oset** [comment]
Follow up in the draft PR [Precinct specific EDFs](https://github.com/ion-oset/nist-1500-examples/pull/1). Includes both precinct specific EDFs and the code that generated them.


- The files in [`precinct-specific-edfs/test_cases/edf_jetsons_precinct_*.json` ](https://github.com/ion-oset/nist-1500-examples/blob/precinct-specific-edfs/test_cases)are EDFs for the four Jetsons precincts.
    - [edf_jetsons_precinct_1.json](https://github.com/ion-oset/nist-1500-examples/blob/precinct-specific-edfs/test_cases/edf_jetsons_precinct_1.json)
    - [edf_jetsons_precinct_2.json](https://github.com/ion-oset/nist-1500-examples/blob/precinct-specific-edfs/test_cases/edf_jetsons_precinct_2.json)
    - [edf_jetsons_precinct_3.json](https://github.com/ion-oset/nist-1500-examples/blob/precinct-specific-edfs/test_cases/edf_jetsons_precinct_3.json)
    - [edf_jetsons_precinct_4.json](https://github.com/ion-oset/nist-1500-examples/blob/precinct-specific-edfs/test_cases/edf_jetsons_precinct_4.json)
- The source files in [precinct-specific-edfs/scripts](https://github.com/ion-oset/nist-1500-examples/tree/precinct-specific-edfs/scripts) provide an implementation, that can make it's way into NISTlib if it makes sense.

**Comment by stratofax** [comment]
The `validate` branch is a dead end, so I merged it back into main and closed this issue. Also, EDF import has been performed successfully elsewhere with the NISTLib code.
