### ISSUE TITLE
Create single-district EDFs for testing

### ISSUE THREAD

**Issue by ion-oset** [TrustTheVote-Project/BallotLab#22]
Ballot PDFs are generated for each district so one or more single district EDFs need to be created for testing.

We are looking into ways to do this extraction automatically, but this issue is simply about generating the files for testing purposes.

**Comment by cwulfman** [comment]
I've updated versasim to support getting electionReport/electionId/precinctId. Please update your instances and give it a try

**Comment by ion-oset** [comment]
See: [Precinct specific EDFs](https://github.com/ion-oset/nist-1500-examples/pull/1) in my [NIST 1500 examples fork](https://github.com/ion-oset/nist-1500-examples/).

This would be a CLI answer that doesn't involve a server of any kind. The only dependency is the [Python NIST data models](https://github.com/ion-oset/nist-data-models/tree/python/main), and it technically doesn't even need that.

**Comment by stratofax** [comment]
Since we now have 4 single-precinct EDFs, this issue is closed! Thanks, @ion-oset
