### ISSUE TITLE
Implement Instructions: Vote Count ("Vote for X")

### ISSUE THREAD

**Issue by stratofax** [TrustTheVote-Project/BallotLab#82]
For each Candidate Contest, the ballot displays instructions on how many candidates you can vote for, like this:

* Vote for 1
* Vote for 2

Retrieve this information from the EDF.

For example:
```
Election.Contest.VoteVariation = "n-of-m"
Election.Contest.VotesAllowed = "4"
```

Voting Instructions question: should "n-of-m" instructions read like this?

> Vote for up to 4

Or this?

> Vote for 

**Answer:** "Vote for up to N" where N is VotesAllowed.

Data consistency question: do all "plurality" type elections require that VotesAllowed = 1?

**Answer:** Plurality is implicitly ... VotesAllowed == 1. That is also true for other VoteVariations as well, but not ones that we are supporting at present. 

_See comments below for details_

**Comment by trustthevote** [comment]
"Vote for up to N" where N is VotesAllowed.

Plurality is implicitly (sorry) VotesAllowed == 1.  That is also true for other VoteVariations as well, but not ones that we are supporting at present. For example, the top two voting method is vote for one, but the tabulation rule is that the top two vote getters "win". Rarely used.

**Comment by stratofax** [comment]
Thanks, @trustthevote I added your answers to the original Issue post (above)
