### ISSUE TITLE
Track Write-In Candidates

### ISSUE THREAD

**Issue by stratofax** [TrustTheVote-Project/BallotLab#84]
Not only does this require a new layout on the PDF ballots, we also need to track the unique ID for each write-in slot, since that’s what’s in the EDF.

Write-in candidates are tagged in the EDF like this:

```
Election.Contest.ContestSelection."IsWriteIn": true
```

So, if a contest has (for example) three write-in candidates, then three separate CandidateSelections (and corresponding IDs) will be tagged with `"IsWriteIn": true`

**Edit**: Track IDs on all candidates not just write-ins.

**Comment by trustthevote** [comment]
Exactly right.
